### PR TITLE
Update AAAX.md

### PR DESCRIPTION
**Pull request by justinformation22**

### CODE REVIEW

**Review by jesusthatsgreat — COMMENTED** [review]
I think DAA descriptions should be written in the 3rd person in order to remain objective. 

I also wouldn't duplicate all content directly from Iconomi DAA pages but using bits of it sparingly is fine if we provide a source and format it as a quote

i.e. In the words of, [DAA manager], the [DAA name] is "bla bla bla bla" - source: [link to Iconomi DAA page]

**Comment by jesusthatsgreat** [comment]
I'll attempt adding content to a DAA page later today and will ask for feedback on it

**Comment by justinformation22** [comment]
The objectiveness comes from their diversification and the numbers. And the managers have already provided the info on what the DAA wants to do and who they are. 
Writing our own summaries is feasible for now, but what when there are over a hundred DAAs? I think it's more convenient to pull that info from the dashboard, that way there also won't be any misunderstandings.

If we go that route, it's indeed nice to at least ask permission from ICONOMI and maybe the manager.

**Comment by jesusthatsgreat** [comment]
The question is if we're just taking the info from Iconomi, why do we need these DAA pages at all? I'd like everything on ICN Hodler to be independent so it acts as a reality-check and offers a different perspective. If we can't keep everything up to date manually, that's fine - in a way it's a good problem to have as it will probably force us to find a way to automate or semi-automate updating.

**Pull request closed without merging**
